/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClipBoardContentJson {
  type: 'file' | 'text'
  content: Array<string>
}
export function getClipboardContent(): ClipBoardContentJson | null
export function onInputEvent(callback: (event: string) => void): void
export function sendKeyboardSimulation(cmd: string): void
export const enum MouseBtn {
  /** Left mouse button */
  Left = 0,
  /** Middle mouse button */
  Middle = 1,
  /** Right mouse button */
  Right = 2,
  /** 4th mouse button. Typically performs the same function as Browser_Back */
  Back = 3,
  /**
   * 5th mouse button. Typically performs the same function as
   * Browser_Forward
   */
  Forward = 4
}
export const enum MouseAction {
  Locaion = 0,
  MoveRelative = 1,
  MoveTo = 2,
  ScrollX = 3,
  ScrollY = 4,
  Up = 5,
  Down = 6,
  Click = 7
}
export interface MouseActionInput {
  action: MouseAction
  data?: Position
  button?: MouseBtn
}
export interface Position {
  x: number
  y: number
}
export function sendMouseSimulation(input: MouseActionInput): Position | null
